source "https://rubygems.org"

gem "middleman"
gem "middleman-syntax"
gem "middleman-autoprefixer"
gem "middleman-blog"
gem "middleman-compass"
gem "compass-blueprint"
gem "redcarpet"
gem "builder"
gem "nokogiri"
